name: Build Kernel

on: workflow_dispatch
jobs:
  build:
    runs-on: warp-custom-kernel
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        submodules: 'true'
    - name: Install Dependencies
      run:  sudo apt-get update && sudo apt-get install -y bison build-essential bc bison curl libssl-dev git zip python3 flex cpio libncurses5-dev lld wget
    - name: Whyred kernel build
      run: ./build.sh whyred

    - name: Upload whyred kernel build
      run:  curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh

    - name: Tulip kernel build
      run: ./build.sh tulip

    - name: Upload tulip kernel build
      run:  curl --upload-file out/arch/arm64/boot/Image.gz-dtb https://transfer.sh
